// Journal Data Models and Validation Schemas
// This file defines the shape of all journal-related data in LifeDash

import { z } from 'zod';
import { Timestamp } from 'firebase/firestore';

// ============================================
// TYPESCRIPT INTERFACES (Cookie Cutters)
// ============================================

/**
 * Journal - A collection of journal entries
 * Example: "Personal Journal", "Dev Diary", "Travel Log"
 */
export interface Journal {
  id: string;                    // Unique identifier (auto-generated by Firestore)
  userId: string;                // Who owns this journal
  name: string;                  // Journal name (e.g., "Personal Journal")
  description: string | null;    // Optional description
  color: string;                 // Color for visual organization (e.g., "#f26419")
  icon: string;                  // Emoji or icon (e.g., "📔")
  entryCount: number;            // How many entries in this journal
  createdAt: Timestamp;          // When was this journal created
  updatedAt: Timestamp;          // Last time any entry was added/modified
}

/**
 * JournalEntry - A single entry within a journal
 * This is where the actual writing/content goes
 */
export interface JournalEntry {
  id: string;                    // Unique identifier
  journalId: string;             // Which journal does this belong to
  userId: string;                // Who wrote this entry
  title: string;                 // Entry title (e.g., "My thoughts on React")
  content: string;               // The actual journal content (rich text/markdown)
  mood: Mood | null;             // Optional mood tracking
  tags: string[];                // Tags for organization (e.g., ["coding", "learning"])
  isFavorite: boolean;           // Star/favorite entries
  createdAt: Timestamp;          // When was this written
  updatedAt: Timestamp;          // Last edit time
}

/**
 * Mood - Predefined moods for mood tracking
 */
export type Mood = 'great' | 'good' | 'okay' | 'bad' | 'terrible';

// Mood options with emojis for the UI
export const MOOD_OPTIONS: { value: Mood; label: string; emoji: string }[] = [
  { value: 'great', label: 'Great', emoji: '😄' },
  { value: 'good', label: 'Good', emoji: '🙂' },
  { value: 'okay', label: 'Okay', emoji: '😐' },
  { value: 'bad', label: 'Bad', emoji: '😟' },
  { value: 'terrible', label: 'Terrible', emoji: '😢' },
];

// ============================================
// ZOD VALIDATION SCHEMAS (Security Guards)
// ============================================

/**
 * Schema for creating a NEW journal
 * Used in forms when user creates a journal
 */
export const createJournalSchema = z.object({
  name: z.string()
    .min(1, 'Journal name is required')
    .max(50, 'Journal name must be less than 50 characters')
    .trim(),
  description: z.string()
    .max(200, 'Description must be less than 200 characters')
    .trim()
    .nullable()
    .optional(),
  color: z.string()
    .regex(/^#[0-9A-F]{6}$/i, 'Must be a valid hex color (e.g., #f26419)')
    .default('#f26419'),
  icon: z.string()
    .min(1, 'Icon is required')
    .max(10, 'Icon must be a single emoji or short text')
    .default('📔'),
});

/**
 * Schema for updating an existing journal
 * All fields are optional (partial update)
 */
export const updateJournalSchema = createJournalSchema.partial();

/**
 * Schema for creating a NEW journal entry
 */
export const createJournalEntrySchema = z.object({
  journalId: z.string()
    .min(1, 'Journal ID is required'),
  title: z.string()
    .min(1, 'Title is required')
    .max(200, 'Title must be less than 200 characters')
    .trim(),
  content: z.string()
    .min(1, 'Content is required')
    .max(50000, 'Content is too long'), // ~50KB limit
  mood: z.enum(['great', 'good', 'okay', 'bad', 'terrible'])
    .nullable()
    .optional(),
  tags: z.array(z.string().trim().toLowerCase())
    .max(10, 'Maximum 10 tags allowed')
    .default([]),
  isFavorite: z.boolean()
    .default(false),
});

/**
 * Schema for updating an existing journal entry
 */
export const updateJournalEntrySchema = createJournalEntrySchema
  .omit({ journalId: true }) // Can't change which journal it belongs to
  .partial();

// ============================================
// TYPESCRIPT TYPES FROM ZOD SCHEMAS
// ============================================

/**
 * Form data types - these are inferred from Zod schemas
 * Use these in your forms/components
 */
export type CreateJournalInput = z.infer<typeof createJournalSchema>;
export type UpdateJournalInput = z.infer<typeof updateJournalSchema>;
export type CreateJournalEntryInput = z.infer<typeof createJournalEntrySchema>;
export type UpdateJournalEntryInput = z.infer<typeof updateJournalEntrySchema>;

// ============================================
// UTILITY TYPES
// ============================================

/**
 * Journal with entry count and latest entry preview
 * Used in dashboard/list views
 */
export interface JournalWithStats extends Journal {
  latestEntry: Pick<JournalEntry, 'id' | 'title' | 'createdAt'> | null;
}

/**
 * Firestore document data (without id)
 * Used when creating new documents
 */
export type JournalData = Omit<Journal, 'id'>;
export type JournalEntryData = Omit<JournalEntry, 'id'>;
